name: fin_zero_id
description: "FinZeroID"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shimmer_animation: ^2.2.1
  #  flutter_vibrate: ^1.3.0
  intl: ^0.19.0
  lottie: ^3.1.3
  get_it: ^8.0.2
  built_value: ^8.9.2
  built_collection: ^5.1.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  camera: ^0.11.0+2
  flutter_nfc_kit: ^3.5.2
  qr_code_scanner_plus: ^2.0.6
  shared_preferences: ^2.3.3
  biometric_storage: ^5.0.1
  cryptography: ^2.7.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.13
  built_value_generator: ^8.9.2
  flutter_launcher_icons: ^0.14.1

dependency_overrides:
  js: ^0.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true